module.exports = {
    switchState: require('./television/viera.switchState'),
    pause : require('./television/viera.pause'),
	play : require('./television/viera.play'),
	stop : require('./television/viera.stopMedia'),
	rewind : require('./television/viera.rewind'),
	fastForward : require('./television/viera.fastForward'),
    volumeUp : require('./television/viera.volumeUp.js'),
    volumeDown : require('./television/viera.volumeDown.js'),
    setVolume : require('./television/viera.setVolume'),
    setMuted : require('./television/viera.setMuted'),
    setChannel : require('./television/viera.setChannel'),
    pressKey : require('./television/viera.pressKey'),
    openMenu : require('./television/viera.openMenu'),
    openInfo : require('./television/viera.openInfo'),
    rec : require('./television/viera.rec'),
    yellowButton : require('./television/viera.yellowButton'),
    skipNext : require('./television/viera.skipNext'),
    skipPrevious : require('./television/viera.skipPrevious'),
};
