module.exports = {
    switchState: require('./television/viera.switchState'),
    pause : require('./television/viera.mediaControl'),
	play : require('./television/viera.mediaControl'),
	stop : require('./television/viera.mediaControl'),
	rewind : require('./television/viera.mediaControl'),
	fastForward : require('./television/viera.mediaControl'),
    volumeUp : require('./television/viera.volumeUp.js'),
    volumeDown : require('./television/viera.volumeDown.js'),
    setVolume : require('./television/viera.setVolume'),
    getVolume : require('./television/viera.getVolume'),
    setMuted : require('./television/viera.setMuted'),
    setChannel : require('./television/viera.setChannel'),
    pressKey : require('./television/viera.pressKey'),
    openMenu : require('./television/viera.openMenu'),
    openInfo : require('./television/viera.openInfo'),
    rec : require('./television/viera.rec'),
    yellowButton : require('./television/viera.yellowButton'),
    skipNext : require('./television/viera.mediaControl'),
    skipPrevious : require('./television/viera.mediaControl'),
};
